//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Subjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class_Subjects()
        {
            this.DivisionClasses = new HashSet<DivisionClasses>();
            this.RegistrationClasses = new HashSet<RegistrationClasses>();
        }

        //public string ErrorClass_Subject { get; set; }
        public string ID { get; set; }
        public string SubjectID { get; set; }
        public string Time { get; set; }
        public string ClassType { get; set; }
        public string Classroom { get; set; }
        public int Quantity { get; set; }
        public string Note { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DivisionClasses> DivisionClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationClasses> RegistrationClasses { get; set; }
    }
}
