//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionClasses
    {
        public int ID { get; set; }
        public string IDTeacher { get; set; }
        public string IDClass { get; set; }

        public string ErrorDivClass { get; set; }

        public virtual Class_Subjects Class_Subjects { get; set; }
        public virtual Users Users { get; set; }
    }
}
