//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageReponse
    {
        public int ID { get; set; }
        public string IDAdmin { get; set; }
        public string MessageAdmin { get; set; }
        public Nullable<System.DateTime> DateRep { get; set; }
    
        public virtual MessageContact MessageContact { get; set; }
        public virtual Users Users { get; set; }
    }
}
