//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolManagementEntities : DbContext
    {
        public SchoolManagementEntities()
            : base("name=SchoolManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class_Subjects> Class_Subjects { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<DivionProjects> DivionProjects { get; set; }
        public virtual DbSet<DivisionClasses> DivisionClasses { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<MessageContact> MessageContact { get; set; }
        public virtual DbSet<MessageReponse> MessageReponse { get; set; }
        public virtual DbSet<RegistrationClasses> RegistrationClasses { get; set; }
        public virtual DbSet<RegistrationSubjects> RegistrationSubjects { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        [DbFunction("SchoolManagementEntities", "CountRegister")]
        public virtual IQueryable<CountRegister_Result> CountRegister()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CountRegister_Result>("[SchoolManagementEntities].[CountRegister]()");
        }
    
        [DbFunction("SchoolManagementEntities", "funClass")]
        public virtual IQueryable<funClass_Result> funClass()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<funClass_Result>("[SchoolManagementEntities].[funClass]()");
        }
    
        [DbFunction("SchoolManagementEntities", "funSubject")]
        public virtual IQueryable<funSubject_Result> funSubject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<funSubject_Result>("[SchoolManagementEntities].[funSubject]()");
        }
    }
}
